// Auto-generated design tokens for React Native
// DO NOT EDIT - Generated by sync-design-system.ts

export const designTokens = {
  "colors": {
    "semantic": {
      "background": {
        "light": "0 0% 100%",
        "dark": "222.2 84% 4.9%"
      },
      "foreground": {
        "light": "222.2 84% 4.9%",
        "dark": "210 40% 98%"
      },
      "card": {
        "light": "0 0% 100%",
        "dark": "222.2 84% 4.9%"
      },
      "card-foreground": {
        "light": "222.2 84% 4.9%",
        "dark": "210 40% 98%"
      },
      "popover": {
        "light": "0 0% 100%",
        "dark": "222.2 84% 4.9%"
      },
      "popover-foreground": {
        "light": "222.2 84% 4.9%",
        "dark": "210 40% 98%"
      },
      "primary": {
        "light": "221.2 83.2% 53.3%",
        "dark": "217.2 91.2% 59.8%"
      },
      "primary-foreground": {
        "light": "210 40% 98%",
        "dark": "222.2 84% 4.9%"
      },
      "secondary": {
        "light": "210 40% 96%",
        "dark": "217.2 32.6% 17.5%"
      },
      "secondary-foreground": {
        "light": "222.2 84% 4.9%",
        "dark": "210 40% 98%"
      },
      "muted": {
        "light": "210 40% 96%",
        "dark": "217.2 32.6% 17.5%"
      },
      "muted-foreground": {
        "light": "215.4 16.3% 46.9%",
        "dark": "215 20.2% 65.1%"
      },
      "accent": {
        "light": "210 40% 96%",
        "dark": "217.2 32.6% 17.5%"
      },
      "accent-foreground": {
        "light": "222.2 84% 4.9%",
        "dark": "210 40% 98%"
      },
      "destructive": {
        "light": "0 84.2% 60.2%",
        "dark": "0 62.8% 30.6%"
      },
      "destructive-foreground": {
        "light": "210 40% 98%",
        "dark": "210 40% 98%"
      },
      "border": {
        "light": "214.3 31.8% 91.4%",
        "dark": "217.2 32.6% 17.5%"
      },
      "input": {
        "light": "214.3 31.8% 91.4%",
        "dark": "217.2 32.6% 17.5%"
      },
      "ring": {
        "light": "221.2 83.2% 53.3%",
        "dark": "224.3 76.3% 94.1%"
      }
    },
    "brand": {
      "petg": {
        "purple": "#8844ee",
        "yellow": "#ffdd22",
        "white": "#ffffff"
      }
    },
    "domain": {
      "health": {
        "primary": "#22c55e",
        "light": "#86efac",
        "dark": "#15803d"
      },
      "connectivity": {
        "primary": "#3b82f6",
        "light": "#93c5fd",
        "dark": "#1d4ed8"
      },
      "activity": {
        "primary": "#a855f7",
        "light": "#d8b4fe",
        "dark": "#7e22ce"
      },
      "neutral": {
        "primary": "#6b7280",
        "light": "#e5e7eb",
        "dark": "#374151"
      }
    },
    "background": {
      "card": "#ffffff",
      "page": "#f9fafb",
      "sidebar": "#f3f4f6"
    },
    "chart": {
      "1": {
        "light": "12 76% 61%",
        "dark": "220 70% 50%"
      },
      "2": {
        "light": "173 58% 39%",
        "dark": "160 60% 45%"
      },
      "3": {
        "light": "197 37% 24%",
        "dark": "30 80% 55%"
      },
      "4": {
        "light": "43 74% 66%",
        "dark": "280 65% 60%"
      },
      "5": {
        "light": "27 87% 67%",
        "dark": "340 75% 55%"
      }
    }
  },
  "spacing": {
    "component": {
      "card": {
        "desktop": "24px",
        "tablet": "20px",
        "mobile": "16px"
      },
      "section": {
        "vertical": "40px",
        "horizontal": "24px"
      }
    },
    "layout": {
      "sidebar": {
        "expanded": "240px",
        "collapsed": "72px"
      },
      "topbar": "64px",
      "container": "2rem"
    },
    "padding": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "0.75rem",
      "lg": "1rem",
      "xl": "1.5rem",
      "2xl": "2rem",
      "3xl": "3rem"
    },
    "margin": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "0.75rem",
      "lg": "1rem",
      "xl": "1.5rem",
      "2xl": "2rem",
      "3xl": "3rem"
    }
  },
  "fonts": {
    "family": {
      "sans": "var(--font-outfit), sans-serif",
      "outfit": "var(--font-outfit), sans-serif"
    },
    "size": {
      "h1": "32px",
      "h2": "28px",
      "h3": "24px",
      "subtitle": "18px",
      "body": "14px",
      "small": "12px",
      "xs": "0.75rem",
      "sm": "0.875rem",
      "base": "1rem",
      "lg": "1.125rem",
      "xl": "1.25rem",
      "2xl": "1.5rem"
    },
    "weight": {
      "normal": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "lineHeight": {
      "tight": "1.2",
      "normal": "1.5",
      "relaxed": "1.75"
    }
  },
  "radii": {
    "none": "0px",
    "sm": "calc(var(--radius) - 4px)",
    "md": "calc(var(--radius) - 2px)",
    "lg": "var(--radius)",
    "xl": "12px",
    "2xl": "16px",
    "3xl": "24px",
    "full": "9999px",
    "card": "12px",
    "button": "8px",
    "pill": "9999px"
  },
  "shadows": {
    "sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    "md": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    "lg": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    "xl": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)"
  },
  "transitions": {
    "default": "200ms ease-in-out",
    "fast": "100ms ease-in-out",
    "slow": "300ms ease-in-out"
  },
  "breakpoints": {
    "mobile": "480px",
    "tablet": "768px",
    "desktop": "1024px",
    "wide": "1280px",
    "2xl": "1400px"
  }
};

export const getColor = (colorPath: string, mode: 'light' | 'dark' = 'light'): string => {
  const pathParts = colorPath.split('.');
  let current: any = designTokens.colors;
  
  for (const part of pathParts) {
    current = current[part];
    if (!current) return '#000000';
  }
  
  if (typeof current === 'object' && current.light && current.dark) {
    return current[mode];
  }
  
  return typeof current === 'string' ? current : '#000000';
};

export default designTokens;
