name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  design-token-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run design token sync
        run: npm run sync-tokens
      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ Design token outputs are out of sync. Please run 'npm run sync-tokens' and commit the changes."
            git status
            exit 1
          fi 